import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal } from "@/context/web3model";
import Header from "@/components/Header";
import { store } from "@/store/store";
import { Provider } from "react-redux";
import ReduxProvider from "@/store/ReduxProvider";
import { GlobalContextProvider } from "@/context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: "#F5F7FB",
        }}
      >
        <GlobalContextProvider>
          <Web3Modal>
            <ReduxProvider>{children}</ReduxProvider>
          </Web3Modal>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
